### ISSUE TITLE
Include actual real-world projects

### ISSUE THREAD

**Issue by wlandau** [wlandau/drake-examples#11]
`drake`'s manual and examples focus on examples small enough to take in at a glance. While this is useful for understanding `drake` itself and generating reprexes in some cases, we examples large enough to fully motivate the problems `drake` is trying to solve. All of my own applications of `drake` are internal to my company an can never be released, so I will need to rely on real use cases from the community. I am thinking of projects like like @pat-s's https://github.com/pat-s/pathogen-modeling. @tiernanmartin and @kendonB, do you have large examples you would be willing to make public.

There are multiple ways we could handle this:

- New directories in the `drake-examples` repo, which would allow users to download and tinker with the code by calling `drake_example()`.
- New chapters in the manual to walk through the project.
- Simply to the [existing list in `drake`'s README](https://github.com/ropensci/drake#real-example-projects).

**Comment by wlandau** [comment]
cc @karthik

**Comment by kendonB** [comment]
I may have a public example available in a few months - hassle me again then. Cheers

**Comment by tiernanmartin** [comment]
Both of my `drake` projects are still in the work-in-progress stage so I'm not ready to open them up to masses just yet.

Let me get back to you once they are completed and published. Thanks for asking!

**Comment by wlandau** [comment]
#16 really helps. Thanks @BListyg!

**Comment by wlandau** [comment]
@kendonB, are you ready to release a public example? Not only would it help document `drake`, it would also allow me to be much more on top of the performance issues you identify in `drake` itself.

**Comment by kendonB** [comment]
Still working through the one mentioned above @wlandau

**Comment by wlandau** [comment]
@kendonB, do you have example ready to share?

**Comment by wlandau** [comment]
We could always have more real-world projects, but I think we're in a better spot than before. Closing because this issue's endgame is vague.
