### ISSUE TITLE
Use RStudio Cloud or BinderHub

### ISSUE THREAD

**Issue by wlandau** [wlandau/drake-examples#12]
Would allow users to run containerized versions of the examples in interactive sessions. https://binderhub.readthedocs.io/en/latest

**Comment by wlandau** [comment]
The current top-level binder workflow takes a long time to build. We should use one per example.

**Comment by wlandau-lilly** [comment]
RStudio cloud might actually be better for this.

**Comment by wlandau** [comment]
Working in an image for the entire repo is problematic because all the dependencies for every example have to be available. We should have gone with a one-repo-per-example strategy from the beginning.
