### ISSUE TITLE
Apply styler and linter to FCD example #21

### ISSUE THREAD

**Issue by benlistyg** [wlandau/drake-examples#26]
Related to #22 for @BListyg 

Need to change:

* Code style
* Spacing / formatting issues
* variable names 

to FCD example

The environment for collaboration should be friendly, inclusive, respectful, and safe for everyone, so all participants must obey [this repository's code of conduct](https://github.com/wlandau/drake-examples/blob/master/CONDUCT.md).

**Comment by wlandau** [comment]
Again, I think I will leave this one to a PR.
