### ISSUE TITLE
Targets without CPU activity on HPC

### ISSUE THREAD

**Issue by pat-s** [wlandau/drake-examples#33]
Hi Will,

so the following bothers me since some months and I am not sure which player in the chain (_clustermq_, _drake_, _parallelMap_) might be the responsible one here.

When starting my workflow via _drake_, I often run ML models on multiple jobs (most often n_jobs = 28) using internal parallelization via _parallelMap_ (which is the parallel library for _mlr_).

Let's say I have 50 settings  ("targets") to run.
The first 28 get distributed across the HPC and all start fine and do their internal parallelization.

Now once one "target" finished, this spawned worker gets assigned the next "target" in the chain, let's say number 29.
Now the following happens for me quite often (= without a clear pattern):
The target starts and appears to be running but the there is no CPU activity anymore in reality.
This goes on infinite until the point when all workers came to the point of having a target running with no CPU activity.

This behavior is different across algorithms:
- Always happens for any new instance of XGBOOST
- Sometimes happens for a new instance of SVM (pkg _kernlab_)
- Rarely happens for a new instance of RF (pkg _ranger_)

This circumstance basically forces me to shut down the whole processing manually and restart fresh. This prevents me from just firing up my workflow on the HPC and forget about it. Often I have to make the decision whether to quit all while some targets are still running (but if 20/28 are "dead" it makes more sense to start fresh).

And there also starts my helplessness here: Which player in the chain might cause this?
At first I thought its a problem of XGBoost since it dominantly appeared there. But it also happens (lately?) for other algs.

_drake_ might not have to do anything with it but I decided for now to open the issue here.
I did not/do not have the time currently to open a test suite trying to narrow down the problematic one in the chain.

- _clustermq_
- _drake_
- pkgs of the ML algs
- _parallelMap_ (since I start sequential runs also via this library it is hard to avoid this one completely)

(I guess a good test setup to exclude would be to use the same code using _mlr3_ which relies on _future_ instead of _parallelMap_.)

While writing about it, I realize that it only happens when benchmarking one of these ML models. I never had such problems for other "targets" running sequential or in parallel.
So I suspect that parallelMap and/or the ML pkgs itself are responsible for it.

Have you ever experienced something similar? (Sorry for the WOT :pray: 	)

**Comment by wlandau** [comment]
This is the first I am hearing about such an issue. When you do get a chance to create a reprex, please let me know. For now, I can think of a few things to try:

- make(parallelism = "future ") with a batchtools backend (bypasses clustermq).
- make(lock_envir = FALSE), as you are already aware.
- Bypass parallelMap, as you mentioned. 
- Are any workers running out of memory? Sometimes that causes silent failures, but you might be able to spot it with clustermq logs.

I do have other ideas, but they require more work.

cc @mschubert

**Comment by pat-s** [comment]
Thanks. I think for now the quickest approach to check if it is related to _parallelMap_ is to try the same setup in _mlr3_. 

Memory should be ok and I also do all the cleaning that is available in _drake_ to start fresh for every new target.
I do not see anything in the logs.

Actually I wanted to post a screenshot showing you all the dead processes on the cluster node with 0 CPU activity while targets appear to be running as normal.

I remember having such issues in the past while running XGBoost standalone. Back then I assumed its a related to the pkg and it is simply like that. This also pushes me more to the direction of _parallelMap_ and assuming that _clustermq_ and _drake_ are fine.
However because I stumble across these issues now when parallelizing on a HPC with _drake_ it could also be a different trigger point. 

Rewriting everything in _mlr3_ might take me a few hours. Seeing the frustration and time I invested in canceling and restarting builds it might be worth it though..

**Comment by mschubert** [comment]
I have seen similar issues very rarely (probably twice in 3 years) when using external packages with *clustermq*. I could never reliably reproduce that, so if you find a simple example that always fails without *drake* please let me know!

Are you sure you're not registering *clustermq*'s `foreach` for *parallelMap*?

**Comment by pat-s** [comment]
I think I might be able to come up with a reprex, though not within the next days (on vacay for 10 days starting tmrw).
Currently trying to replicate it using _mlr3_ without _parallelMap_ to narrow it down.

> Are you sure you're not registering clustermq's foreach for parallelMap?

I don't quite get what you mean here. Could you give a bit more detail on this? I am not doing any specific registering somewhere.

**Comment by pat-s** [comment]
One problem with the _mlr3_ example is that the issue most often occurs with _xgboost_ but this learner is not yet available for _mlr3_. Trying it with _ranger_ and _kernlab_ only might not be a robust one. But step by step..

**Comment by pat-s** [comment]
We tracked it down to be an issue of the "multicore" parallel mode. Discussion continuing [here](https://github.com/berndbischl/parallelMap/issues/72#issuecomment-528777954).
