### ISSUE TITLE
script-based workflows

### ISSUE THREAD

**Issue by thebioengineer** [wlandau/drake-examples#35]
Before posting

The environment for collaboration should be friendly, inclusive, respectful, and safe for everyone, so all participants must obey [this repository's code of conduct](https://github.com/wlandau/drake-examples/blob/master/CONDUCT.md).

Given that we now have a plan for how we intend on approaching script-based workflows, I feel as though an explicit example would be good. In addition, we could then put an additional solution to the questions surrounding using [script workflows](https://twitter.com/ibddoctor/status/1039087657979179008).

**Comment by wlandau** [comment]
Great idea! I will try to review your PR by the end of this week.

**Comment by thebioengineer** [comment]
resolved with merging of pull request #36
